php_src/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\DoctrineProductRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Ramsey\Uuid\UuidInterface;

/**
 * @ORM\Entity(repositoryClass=DoctrineProductRepository::class)
 */
class Product
{
    /**
     * @var UuidInterface
     *
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @var integer
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @var string
     * @ORM\Column(type="string", length=3)
     */
    private $currency;

    /**
     * @var \DateTimeInterface
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @return UuidInterface
     */
    public function getId(): UuidInterface
    {
        return $this->id;
    }

    /**
     * @param UuidInterface $id
     */
    public function setId(UuidInterface $id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * @return int
     */
    public function getPrice(): int
    {
        return $this->price;
    }

    /**
     * @param int $price
     */
    public function setPrice(int $price): void
    {
        $this->price = $price;
    }

    /**
     * @return string
     */
    public function getCurrency(): string
    {
        return $this->currency;
    }

    /**
     * @param string $currency
     */
    public function setCurrency(string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getCreatedAt(): \DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTimeInterface $createdAt
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return float|int
     */
    public function getFormattedPrice(){
        return ($this->getPrice()) ? ($this->getPrice() / 100) : 0;
    }
}

php_src/templates/product/form.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    <h2>Create new product:</h2>
    <div class="product-form">
        {{ form_start(form) }}
            <div class="errors-container">
                {{ form_errors(form) }}
            </div>

            <div class="form-element-wrapper">
                {{ form_label(form.name) }}
                {{ form_widget(form.name) }}
                <div class="form-error">
                    {{ form_errors(form.name) }}
                </div>
            </div>

            <div class="form-element-wrapper">
                {{ form_label(form.price) }}
                {{ form_widget(form.price) }}
                {{ form_widget(form.currency) }}
                <div class="form-error">
                    {{ form_errors(form.price) }}
                </div>
            </div>
            <div class="form-element-wrapper">
                {{ form_label(form.description) }}
                <div class="description-control-wrapper">
                    {{ form_widget(form.description) }}
                </div>
                <div class="form-error">
                    {{ form_errors(form.description) }}
                </div>
            </div>

        {{ form_end(form) }}
    </div>


{% endblock %}

php_src/templates/product/list.html.twig
{% extends 'base.html.twig' %}
{% block content %}
    <div class="product-list">
        {% if app.user and is_granted('ROLE_ADMIN')%}
            <div class="product-list-create-button-container">
                <a href="{{ path('create_product') }}">Add new product</a>
            </div>
        {% endif %}
    {% for product in pagination %}
        <div class="product-list-item" data-id="{{ product.id }}">
            <div class="summary">
                <div class="product-name">{{ product.name }}</div>
                <div class="price">Price: {{ product.formattedPrice }} {{ product.currency }}</div>
                <div class="date-added">Added: {{ product.createdAt | date('Y-m-d') }}, {{ product.createdAt | date('H:i:s') }}</div>
            </div>
            <div class="info">
                <div class="product-desc">{{ product.description }}</div>
            </div>
        </div>

    {% endfor %}
    </div>
<div class="navigation">
    {{ knp_pagination_render(pagination) }}
</div>


{% endblock %}